### PR TITLE
🐛 Fix Alphabetical Sorting

### LINKED ISSUE #157: 🐛 Incorrect Alphabetical Sorting with Emojis in Task Titles
## 🐛 Bug Description

When attempting to sort tasks alphabetically, titles containing emojis are not sorted correctly. The sorting logic appears to treat emojis as characters that influence the alphabetical order, leading to an illogical display order of task titles.

## 🔁 Steps to Reproduce
1. Navigate to the Task List view.
2. Create or ensure there are tasks with titles that include emojis (e.g., "✨ Task A", "🎉 Task B", "🚀 Task C").
3. Apply the "Sort Alphabetically" filter to the task list.
4. Observe the sorted order.

## 🤔 Expected Behavior

When the "Sort Alphabetically" filter is applied, I expect the task titles to be sorted based purely on their alphanumeric characters, ignoring or properly handling emojis so they do not disrupt the intended alphabetical order. For example, "✨ Task A" should appear before "🎉 Task B " if sorted alphabetically by "Task A" and "Task B".

### PR DESCRIPTION
**Pull request by roternando**
This pull request updates the sorting logic in the `TaskListViewModel` class to improve the handling of task titles during alphabetical sorting. The change ensures that non-alphanumeric characters are ignored and comparisons are case-insensitive.

### Sorting logic improvement:
* [`lib/ui/task_list/task_list_view_model.dart`](diffhunk://#diff-1a3be1eae8760a26190de5ca21f4e2156cf27c26cb875fce6a098257e8c30f93L108-R115): Modified the alphabetical sorting logic to normalize task titles by removing non-alphanumeric characters and converting them to lowercase before comparison. This ensures a more user-friendly and consistent sorting behavior.

### CODE REVIEW

**Review by Friedinger — CHANGES_REQUESTED** [review]

File: lib/ui/task_list/task_list_view_model.dart [hunk 1]
```diff
@@ -129,7 +129,14 @@ class TaskListViewModel extends ChangeNotifier {
 
   List<Task> _sortTasks(final List<Task> tasks, final String sort) {
     if (sort == "Alphabetical") {
-      return tasks..sort((final a, final b) => a.title.compareTo(b.title));
+      tasks.sort(
```
Comment (Friedinger) [inline lib/ui/task_list/task_list_view_model.dart:132]: The `return` is missing here, or is this intentionally?

**Review by Friedinger — CHANGES_REQUESTED** [review]

**Review by Friedinger — APPROVED** [review]

**Review by IamPekka058 — APPROVED** [review]
